//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dihiddieDiary.DAL.DiaryPost.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class diary_post
    {
        public int id { get; set; }
        public string title { get; set; }
        public System.DateTime createDateTime { get; set; }
        public Nullable<System.DateTime> updateDateTime { get; set; }
        public byte[] content { get; set; }
    }
}
